name: billbronew
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  pin_code_fields: ^8.0.1
  printing: ^5.11.1
  pdf: ^3.10.7


  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  intl: ^0.20.2
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/fa-solid-900.ttf
    - lib/assets/fa-brands-400.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/logo.png"

